//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSA01.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesRecibo : DbContext
    {
        public EntitiesRecibo()
            : base("name=EntitiesRecibo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SAG01_CORRELATIVO> SAG01_CORRELATIVO { get; set; }
        public DbSet<SAG01_EVENTO> SAG01_EVENTO { get; set; }
        public DbSet<SAG01_EVENTO_OPCION> SAG01_EVENTO_OPCION { get; set; }
        public DbSet<SAG01_PAIS> SAG01_PAIS { get; set; }
        public DbSet<SAG01_RECIBO> SAG01_RECIBO { get; set; }
        public DbSet<SAG01_REGION> SAG01_REGION { get; set; }
        public DbSet<SAG01_USUARIO> SAG01_USUARIO { get; set; }
    }
}
