//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSA01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAG01_CORRELATIVO
    {
        public decimal CORRELATIVO { get; set; }
        public Nullable<decimal> CORRELATIVO_DISPONIBLE { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
